### ISSUE TITLE
ArgumentError: wrong number of arguments

### ISSUE THREAD

**Issue by Awlter** [ankane/searchkick#1201]
Hi searchkick team, I am facing two weird problems after making one of my model to reindex using queuing.

```
class OneOfMyModel
    searchkick callback: :queue
end
...
#config/initializer/searchkick.rb
Searchkick.redis = ConnectionPool.new { Redis.new(url: "redis://#{ENV['WEB_REDIS_HOST']}:#{ENV['WEB_REDIS_PORT']}/1") }
```
I use sidekiq-cron to call `Searchkick::ProcessQueueJob.perform_later(class_name: "MyModel")` periodically with an activejob.

Reindexing MyModel with queueing throws `ArgumentError: wrong number of arguments (given 1, expected 0)`:
```
/gems/searchkick-3.1.0/lib/searchkick/process_queue_job.rb:5 in perform
/gems/activejob_backport-0.0.3/lib/active_job/execution.rb:31 in block in perform_now
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:117 in call
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:555 in block (2 levels) in compile
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505 in call
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:498 in block (2 levels) in around
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:343 in block (2 levels) in simple
/gems/sentry-raven-2.7.3/lib/raven/integrations/rails/active_job.rb:18 in capture_and_reraise_with_sentry
/gems/sentry-raven-2.7.3/lib/raven/integrations/rails/active_job.rb:12 in block (2 levels) in included
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:441 in instance_exec
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:441 in block in make_lambda
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:342 in block in simple
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:497 in block in around
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505 in call
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:498 in block (2 levels) in around
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:343 in block (2 levels) in simple
/gems/activejob_backport-0.0.3/lib/active_job/logging.rb:24 in block (4 levels) in <module:Logging>
/gems/activesupport-4.2.5/lib/active_support/notifications.rb:164 in block in instrument
/gems/activesupport-4.2.5/lib/active_support/notifications/instrumenter.rb:20 in instrument
/gems/activesupport-4.2.5/lib/active_support/notifications.rb:164 in instrument
/gems/activejob_backport-0.0.3/lib/active_job/logging.rb:23 in block (3 levels) in <module:Logging>
/gems/activejob_backport-0.0.3/lib/active_job/logging.rb:61 in block in tag_logger
/gems/activesupport-4.2.5/lib/active_support/tagged_logging.rb:68 in block in tagged
/gems/activesupport-4.2.5/lib/active_support/tagged_logging.rb:26 in tagged
/gems/activesupport-4.2.5/lib/active_support/tagged_logging.rb:68 in tagged
/gems/activejob_backport-0.0.3/lib/active_job/logging.rb:61 in tag_logger
/gems/activejob_backport-0.0.3/lib/active_job/logging.rb:20 in block (2 levels) in <module:Logging>
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:441 in instance_exec
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:441 in block in make_lambda
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:342 in block in simple
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:497 in block in around
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505 in call
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:92 in __run_callbacks__
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778 in _run_perform_callbacks
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:81 in run_callbacks
/gems/activejob_backport-0.0.3/lib/active_job/execution.rb:30 in perform_now
/gems/activejob_backport-0.0.3/lib/active_job/execution.rb:20 in execute
/gems/activejob_backport-0.0.3/lib/active_job/queue_adapters/sidekiq_adapter.rb:30 in perform
/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:185 in execute_job
/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:167 in block (2 levels) in process
/gems/sidekiq-5.2.1/lib/sidekiq/middleware/chain.rb:128 in block in invoke
/gems/sentry-raven-2.7.3/lib/raven/integrations/sidekiq.rb:9 in call
/gems/sidekiq-5.2.1/lib/sidekiq/middleware/chain.rb:130 in block in invoke
/gems/sidekiq-5.2.1/lib/sidekiq/middleware/chain.rb:133 in invoke
/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:166 in block in process
/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:137 in block (6 levels) in dispatch
/gems/sidekiq-5.2.1/lib/sidekiq/job_retry.rb:98 in local
/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:136 in block (5 levels) in dispatch
/gems/sidekiq-5.2.1/lib/sidekiq.rb:36 in block in <module:Sidekiq>
/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:132 in block (4 levels) in dispatch
/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:217 in stats
/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:127 in block (3 levels) in dispatch
/gems/sidekiq-5.2.1/lib/sidekiq/job_logger.rb:8 in call
/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:126 in block (2 levels) in dispatch
/gems/sidekiq-5.2.1/lib/sidekiq/job_retry.rb:73 in global
/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:125 in block in dispatch
/gems/sidekiq-5.2.1/lib/sidekiq/logging.rb:48 in with_context
/gems/sidekiq-5.2.1/lib/sidekiq/logging.rb:42 in with_job_hash_context
/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:124 in dispatch
/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:165 in process
/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:83 in process_one
/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:71 in run
/gems/sidekiq-5.2.1/lib/sidekiq/util.rb:16 in watchdog
/gems/sidekiq-5.2.1/lib/sidekiq/util.rb:25 in block in safe_thread
```
My other model are still using async to reindex, and the job throws `ArgumentError: wrong number of arguments (given 4, expected 2..3)`
```
/gems/searchkick-3.1.0/lib/searchkick/reindex_v2_job.rb:12 in perform
/gems/activejob_backport-0.0.3/lib/active_job/execution.rb:31 in block in perform_now
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:117 in call
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:555 in block (2 levels) in compile
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505 in call
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:498 in block (2 levels) in around
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:343 in block (2 levels) in simple
/gems/sentry-raven-2.7.3/lib/raven/integrations/rails/active_job.rb:18 in capture_and_reraise_with_sentry
/gems/sentry-raven-2.7.3/lib/raven/integrations/rails/active_job.rb:12 in block (2 levels) in included
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:441 in instance_exec
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:441 in block in make_lambda
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:342 in block in simple
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:497 in block in around
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505 in call
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:498 in block (2 levels) in around
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:343 in block (2 levels) in simple
/gems/activejob_backport-0.0.3/lib/active_job/logging.rb:24 in block (4 levels) in <module:Logging>
/gems/activesupport-4.2.5/lib/active_support/notifications.rb:164 in block in instrument
/gems/activesupport-4.2.5/lib/active_support/notifications/instrumenter.rb:20 in instrument
/gems/activesupport-4.2.5/lib/active_support/notifications.rb:164 in instrument
/gems/activejob_backport-0.0.3/lib/active_job/logging.rb:23 in block (3 levels) in <module:Logging>
/gems/activejob_backport-0.0.3/lib/active_job/logging.rb:61 in block in tag_logger
/gems/activesupport-4.2.5/lib/active_support/tagged_logging.rb:68 in block in tagged
/gems/activesupport-4.2.5/lib/active_support/tagged_logging.rb:26 in tagged
/gems/activesupport-4.2.5/lib/active_support/tagged_logging.rb:68 in tagged
/gems/activejob_backport-0.0.3/lib/active_job/logging.rb:61 in tag_logger
/gems/activejob_backport-0.0.3/lib/active_job/logging.rb:20 in block (2 levels) in <module:Logging>
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:441 in instance_exec
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:441 in block in make_lambda
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:342 in block in simple
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:497 in block in around
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505 in call
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:92 in __run_callbacks__
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778 in _run_perform_callbacks
/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:81 in run_callbacks
/gems/activejob_backport-0.0.3/lib/active_job/execution.rb:30 in perform_now
/gems/activejob_backport-0.0.3/lib/active_job/execution.rb:20 in execute
/gems/activejob_backport-0.0.3/lib/active_job/queue_adapters/sidekiq_adapter.rb:30 in perform
/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:185 in execute_job
/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:167 in block (2 levels) in process
/gems/sidekiq-5.2.1/lib/sidekiq/middleware/chain.rb:128 in block in invoke
/gems/sentry-raven-2.7.3/lib/raven/integrations/sidekiq.rb:9 in call
/gems/sidekiq-5.2.1/lib/sidekiq/middleware/chain.rb:130 in block in invoke
/gems/sidekiq-5.2.1/lib/sidekiq/middleware/chain.rb:133 in invoke
/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:166 in block in process
/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:137 in block (6 levels) in dispatch
/gems/sidekiq-5.2.1/lib/sidekiq/job_retry.rb:98 in local
/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:136 in block (5 levels) in dispatch
/gems/sidekiq-5.2.1/lib/sidekiq.rb:36 in block in <module:Sidekiq>
/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:132 in block (4 levels) in dispatch
/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:217 in stats
/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:127 in block (3 levels) in dispatch
/gems/sidekiq-5.2.1/lib/sidekiq/job_logger.rb:8 in call
/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:126 in block (2 levels) in dispatch
/gems/sidekiq-5.2.1/lib/sidekiq/job_retry.rb:73 in global
/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:125 in block in dispatch
/gems/sidekiq-5.2.1/lib/sidekiq/logging.rb:48 in with_context
/gems/sidekiq-5.2.1/lib/sidekiq/logging.rb:42 in with_job_hash_context
/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:124 in dispatch
/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:165 in process
/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:83 in process_one
/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:71 in run
/gems/sidekiq-5.2.1/lib/sidekiq/util.rb:16 in watchdog
/gems/sidekiq-5.2.1/lib/sidekiq/util.rb:25 in block in safe_thread
```

Here is my Gemfile.lock:
```
GIT
  remote: git://github.com/PingPlusPlus/pingpp-ruby.git
  revision: b59a4188bd1bca54e1f5cff821f03f25768f0873
  specs:
    pingpp (2.2.0)
      rest-client (>= 1.4, < 4.0)

GIT
  remote: git://github.com/qiniu/ruby-sdk.git
  revision: c4ea5334e0ea3151ad8f5eaf7e1405e67eda7afa
  specs:
    qiniu (6.9.0)
      mime-types (~> 3.1)
      rest-client (~> 2.0)

GIT
  remote: git://github.com/ruby-grape/grape-swagger.git
  revision: d6bed9523344115e7786e8161de14af93aa067b9
  specs:
    grape-swagger (0.27.3)
      grape (>= 0.16.2)

GIT
  remote: git://github.com/yuanping/select2_simple_form.git
  revision: 811a00f06c445e6373de9b428185d709555c0753
  specs:
    select2_simple_form (0.7.3)
      rails (> 4.0.0)
      select2-rails (~> 3.5.2)

GIT
  remote: git://github.com/yuanping/tilt-jbuilder.git
  revision: 5b158dd519667edffdf0c91001137af34766230c
  branch: cache
  specs:
    tilt-jbuilder (0.7.1)
      jbuilder
      tilt (>= 1.3.0, < 3)

GIT
  remote: git://github.com/yuanping/x-editable-rails.git
  revision: 9a8e9bbd67f210db1c90a87edaa0644f80194713
  specs:
    x-editable-rails (1.5.5)
      railties

GIT
  remote: https://github.com/inventionlabsSydney/capistrano-sneakers.git
  revision: d2a495c1e0a062d1864247a33c02989c80999829
  specs:
    capistrano-sneakers (0.0.1)
      capistrano (>= 3.9.0)
      sneakers

GEM
  remote: https://gems.ruby-china.com/
  specs:
    aasm (4.12.2)
      concurrent-ruby (~> 1.0)
    actionmailer (4.2.5)
      actionpack (= 4.2.5)
      actionview (= 4.2.5)
      activejob (= 4.2.5)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.5)
      actionview (= 4.2.5)
      activesupport (= 4.2.5)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionpack-action_caching (1.2.0)
      actionpack (>= 4.0.0, < 6)
    actionpack-page_caching (1.1.0)
      actionpack (>= 4.0.0, < 6)
    actionview (4.2.5)
      activesupport (= 4.2.5)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    active_attr (0.10.2)
      activemodel (>= 3.0.2, < 5.2)
      activesupport (>= 3.0.2, < 5.2)
    active_interaction (3.5.2)
      activemodel (>= 4, < 6)
    activejob (4.2.5)
      activesupport (= 4.2.5)
      globalid (>= 0.3.0)
    activejob_backport (0.0.3)
      activesupport (>= 4.0.0)
    activemodel (4.2.5)
      activesupport (= 4.2.5)
      builder (~> 3.1)
    activerecord (4.2.5)
      activemodel (= 4.2.5)
      activesupport (= 4.2.5)
      arel (~> 6.0)
    activerecord-import (0.25.0)
      activerecord (>= 3.2)
    activesupport (4.2.5)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    addressable (2.5.2)
      public_suffix (>= 2.0.2, < 4.0)
    airbrake (6.2.1)
      airbrake-ruby (~> 2.3, >= 2.3.1)
    airbrake-ruby (2.3.2)
    airbrussh (1.3.0)
      sshkit (>= 1.6.1, != 1.7.0)
    amq-protocol (2.2.0)
    ansi (1.5.0)
    arel (6.0.4)
    ast (2.4.0)
    autoprefixer-rails (7.1.3)
      execjs
    awesome_print (1.8.0)
    axiom-types (0.1.1)
      descendants_tracker (~> 0.0.4)
      ice_nine (~> 0.11.0)
      thread_safe (~> 0.3, >= 0.3.1)
    bcrypt (3.1.11)
    better_errors (2.3.0)
      coderay (>= 1.0.0)
      erubi (>= 1.0.0)
      rack (>= 0.9.0)
    bh (1.3.6)
      actionpack
      activesupport
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    bootflat-rails (0.2.1)
      bootstrap-sass (~> 3.1)
      jquery-rails (~> 3.1)
      sass (~> 3.3)
    bootstrap-kaminari-views (0.0.5)
      kaminari (>= 0.13)
      rails (>= 3.1)
    bootstrap-sass (3.3.7)
      autoprefixer-rails (>= 5.2.1)
      sass (>= 3.3.4)
    browser (2.5.0)
    bson (4.3.0)
    bson_ext (1.5.1)
    builder (3.2.3)
    bullet (5.6.1)
      activesupport (>= 3.0.0)
      uniform_notifier (~> 1.10.0)
    bunny (2.6.6)
      amq-protocol (>= 2.1.0)
    cancancan (2.0.0)
    capistrano (3.10.1)
      airbrussh (>= 1.0.0)
      i18n
      rake (>= 10.0.0)
      sshkit (>= 1.9.0)
    capistrano-bundler (1.2.0)
      capistrano (~> 3.1)
      sshkit (~> 1.2)
    capistrano-passenger (0.2.0)
      capistrano (~> 3.0)
    capistrano-rails (1.3.0)
      capistrano (~> 3.1)
      capistrano-bundler (~> 1.1)
    capistrano-rvm (0.1.2)
      capistrano (~> 3.0)
      sshkit (~> 1.2)
    capistrano-sidekiq (1.0.0)
      capistrano (>= 3.9.0)
      sidekiq (>= 3.4)
    capybara (2.15.1)
      addressable
      mini_mime (>= 0.1.3)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    chunky_png (1.3.8)
    cocoon (1.2.10)
    coderay (1.1.2)
    coercible (1.0.0)
      descendants_tracker (~> 0.0.1)
    coffee-rails (4.0.1)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.12.2)
    colorize (0.8.1)
    compass (1.0.3)
      chunky_png (~> 1.2)
      compass-core (~> 1.0.2)
      compass-import-once (~> 1.0.5)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
      sass (>= 3.3.13, < 3.5)
    compass-core (1.0.3)
      multi_json (~> 1.0)
      sass (>= 3.3.0, < 3.5)
    compass-import-once (1.0.5)
      sass (>= 3.2, < 3.5)
    compass-rails (3.0.2)
      compass (~> 1.0.0)
      sass-rails (< 5.1)
      sprockets (< 4.0)
    concurrent-ruby (1.0.5)
    config (1.4.0)
      activesupport (>= 3.0)
      deep_merge (~> 1.1.1)
    connection_pool (2.2.2)
    crack (0.4.3)
      safe_yaml (~> 1.0.0)
    crass (1.0.4)
    css_parser (1.5.0)
      addressable
    daemons (1.2.4)
    dalli (2.7.6)
    database_cleaner (1.6.1)
    debug_inspector (0.0.3)
    deep_merge (1.1.1)
    descendants_tracker (0.0.4)
      thread_safe (~> 0.3, >= 0.3.1)
    devise (4.3.0)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0, < 5.2)
      responders
      warden (~> 1.2.3)
    diff-lcs (1.3)
    domain_name (0.5.20170404)
      unf (>= 0.0.5, < 1.0.0)
    dotenv (2.2.1)
    dotenv-rails (2.2.1)
      dotenv (= 2.2.1)
      railties (>= 3.2, < 5.2)
    elasticsearch (6.1.0)
      elasticsearch-api (= 6.1.0)
      elasticsearch-transport (= 6.1.0)
    elasticsearch-api (6.1.0)
      multi_json
    elasticsearch-transport (6.1.0)
      faraday
      multi_json
    enumerize (2.1.2)
      activesupport (>= 3.2)
    equalizer (0.0.11)
    erubi (1.6.1)
    erubis (2.7.0)
    et-orbi (1.1.4)
      tzinfo
    eventmachine (1.2.5)
    execjs (2.7.0)
    factory_girl (4.8.0)
      activesupport (>= 3.0.0)
    factory_girl_rails (4.8.0)
      factory_girl (~> 4.8.0)
      railties (>= 3.0.0)
    faker (1.8.4)
      i18n (~> 0.5)
    faraday (0.15.2)
      multipart-post (>= 1.2, < 3)
    ffi (1.9.25)
    font-awesome-rails (4.7.0.4)
      railties (>= 3.2, < 6.0)
    formatador (0.2.5)
    fugit (1.1.5)
      et-orbi (~> 1.1, >= 1.1.3)
      raabro (~> 1.1)
    geocoder (1.4.4)
    globalid (0.4.1)
      activesupport (>= 4.2.0)
    gon (6.1.0)
      actionpack (>= 3.0)
      json
      multi_json
      request_store (>= 1.0)
    grape (0.19.1)
      activesupport
      builder
      hashie (>= 2.1.0)
      multi_json (>= 1.3.2)
      multi_xml (>= 0.5.2)
      mustermann-grape (~> 0.4.0)
      rack (>= 1.3.0)
      rack-accept
      virtus (>= 1.0.0)
    grape-entity (0.6.0)
      activesupport
      multi_json (>= 1.3.2)
    grape-jbuilder (0.2.0)
      grape (>= 0.3)
      i18n
      jbuilder
      tilt
      tilt-jbuilder (>= 0.4.0)
    grape-kaminari (0.1.9)
      grape
      kaminari
    grape-route-helpers (2.0.0)
      activesupport
      grape (~> 0.16, >= 0.16.0)
      rake
    grape-swagger-entity (0.2.1)
      grape-entity (>= 0.5.0)
      grape-swagger (>= 0.20.4)
    grape-swagger-rails (0.3.0)
      railties (>= 3.2.12)
    grape_logging (1.5.0)
      grape
    grim (1.3.3)
    guard (2.14.2)
      formatador (>= 0.2.4)
      listen (>= 2.7, < 4.0)
      lumberjack (>= 1.0.12, < 2.0)
      nenv (~> 0.1)
      notiffany (~> 0.0)
      pry (>= 0.9.12)
      shellany (~> 0.0)
      thor (>= 0.18.1)
    guard-compat (1.2.1)
    guard-rspec (4.7.3)
      guard (~> 2.1)
      guard-compat (~> 1.1)
      rspec (>= 2.99.0, < 4.0)
    guard-rubocop (1.3.0)
      guard (~> 2.0)
      rubocop (~> 0.20)
    guess_html_encoding (0.0.11)
    hashdiff (0.3.6)
    hashie (3.6.0)
    hashie-forbidden_attributes (0.1.1)
      hashie (>= 3.0)
    hiredis (0.4.5)
    htmlentities (4.3.4)
    http-cookie (1.0.3)
      domain_name (~> 0.5)
    httparty (0.13.7)
      json (~> 1.8)
      multi_xml (>= 0.5.2)
    i18n (0.8.6)
    ice_nine (0.11.2)
    ionicons-rails (2.0.0)
    jaro_winkler (1.5.1)
    jbuilder (2.1.1)
      activesupport (>= 3.0.0, < 5)
      multi_json (~> 1.2)
    jquery-rails (3.1.4)
      railties (>= 3.0, < 5.0)
      thor (>= 0.14, < 2.0)
    json (1.8.6)
    json-schema (2.8.0)
      addressable (>= 2.4)
    json_spec (1.1.5)
      multi_json (~> 1.0)
      rspec (>= 2.0, < 4.0)
    kaminari (1.0.1)
      activesupport (>= 4.1.0)
      kaminari-actionview (= 1.0.1)
      kaminari-activerecord (= 1.0.1)
      kaminari-core (= 1.0.1)
    kaminari-actionview (1.0.1)
      actionview
      kaminari-core (= 1.0.1)
    kaminari-activerecord (1.0.1)
      activerecord
      kaminari-core (= 1.0.1)
    kaminari-core (1.0.1)
    kaminari-grape (1.0.1)
      grape
      kaminari-core (~> 1.0)
    kaminari-mongoid (1.0.1)
      kaminari-core (~> 1.0)
      mongoid
    launchy (2.4.3)
      addressable (~> 2.3)
    letter_opener (1.4.1)
      launchy (~> 2.2)
    letter_opener_web (1.2.3)
      letter_opener (~> 1.0)
      rails (>= 3.2)
    libv8 (3.16.14.19)
    listen (3.1.5)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
      ruby_dep (~> 1.2)
    logstash-event (1.2.02)
    logstash-logger (0.25.1)
      logstash-event (~> 1.2)
    loofah (2.2.2)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    lumberjack (1.0.13)
    mail (2.7.0)
      mini_mime (>= 0.1.1)
    method_source (0.8.2)
    middleware (0.1.0)
    mime-types (3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2016.0521)
    mini_magick (4.9.2)
    mini_mime (0.1.4)
    mini_portile (0.6.2)
    minitest (5.11.3)
    monetize (1.7.0)
      money (~> 6.9)
    money (6.9.0)
      i18n (>= 0.6.4, < 0.9)
    money-rails (1.9.0)
      activesupport (>= 3.0)
      monetize (~> 1.7.0)
      money (~> 6.9.0)
      railties (>= 3.0)
    mongo (2.6.2)
      bson (>= 4.3.0, < 5.0.0)
    mongoid (5.4.0)
      activemodel (~> 4.0)
      mongo (>= 2.5.1, < 3.0.0)
      origin (~> 2.3)
      tzinfo (>= 0.3.37)
    mongoid-autoinc (5.0.2)
      mongoid (~> 5.0)
    mongoid-compatibility (0.5.1)
      activesupport
      mongoid (>= 2.0)
    mongoid-geospatial (5.0.0)
      mongoid (>= 5.0.0.beta)
    mongoid-locker (0.3.5)
      mongoid (>= 2.8)
      mongoid-compatibility (>= 0.4.1)
    mongoid-rspec (4.0.0)
      activesupport (>= 3.0.0)
      mongoid (>= 2.0)
      mongoid-compatibility
      rspec (~> 3.3)
    mongoid-tree (2.1.0)
      mongoid (>= 4.0, < 7.0)
    mongoid_paranoia (0.2.1)
      mongoid (>= 4)
      mongoid-compatibility
    multi_json (1.13.1)
    multi_xml (0.6.0)
    multipart-post (2.0.0)
    mustermann (0.4.0)
      tool (~> 0.2)
    mustermann-grape (0.4.0)
      mustermann (= 0.4.0)
    mysql2 (0.4.10)
    nenv (0.3.0)
    net-scp (1.2.1)
      net-ssh (>= 2.6.5)
    net-ssh (4.2.0)
    netrc (0.11.0)
    nokogiri (1.6.6.2)
      mini_portile (~> 0.6.0)
    notiffany (0.1.1)
      nenv (~> 0.1)
      shellany (~> 0.0)
    oga (2.10)
      ast
      ruby-ll (~> 2.1)
    oj (3.3.5)
    origin (2.3.1)
    orm_adapter (0.5.0)
    parallel (1.12.1)
    parallel_tests (2.14.3)
      parallel
    parser (2.5.1.2)
      ast (~> 2.4.0)
    phonelib (0.6.24)
    photoswipe-rails (4.1.2)
    pili (1.5.5)
      httparty (~> 0.13.3)
    powerpack (0.1.2)
    premailer (1.10.4)
      addressable
      css_parser (>= 1.4.10)
      htmlentities (>= 4.0.0)
    premailer-rails (1.9.7)
      actionmailer (>= 3, < 6)
      premailer (~> 1.7, >= 1.7.9)
    protobuf (3.7.5)
      activesupport (>= 3.2)
      middleware
      thor
      thread_safe
    pry (0.10.4)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    pry-nav (0.2.4)
      pry (>= 0.9.10, < 0.11.0)
    pry-rails (0.3.6)
      pry (>= 0.10.4)
    public_activity (1.5.0)
      actionpack (>= 3.0.0)
      activerecord (>= 3.0)
      i18n (>= 0.5.0)
      railties (>= 3.0.0)
    public_suffix (3.0.0)
    quiet_assets (1.1.0)
      railties (>= 3.1, < 5.0)
    raabro (1.1.6)
    rack (1.6.10)
    rack-accept (0.4.5)
      rack (>= 0.4)
    rack-cors (1.0.1)
    rack-protection (1.5.5)
      rack
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.2.5)
      actionmailer (= 4.2.5)
      actionpack (= 4.2.5)
      actionview (= 4.2.5)
      activejob (= 4.2.5)
      activemodel (= 4.2.5)
      activerecord (= 4.2.5)
      activesupport (= 4.2.5)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.5)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.9)
      activesupport (>= 4.2.0, < 5.0)
      nokogiri (~> 1.6)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.4)
      loofah (~> 2.2, >= 2.2.2)
    railties (4.2.5)
      actionpack (= 4.2.5)
      activesupport (= 4.2.5)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rainbow (3.0.0)
    rake (12.3.1)
    rb-fsevent (0.10.3)
    rb-inotify (0.9.10)
      ffi (>= 0.5.0, < 2)
    rchardet19 (1.3.7)
    redis (3.3.5)
    redis_rate_limiter (0.1.0)
      redis
    ref (2.0.0)
    request_store (1.3.2)
    responders (2.4.0)
      actionpack (>= 4.2.0, < 5.3)
      railties (>= 4.2.0, < 5.3)
    rest-client (2.0.2)
      http-cookie (>= 1.0.2, < 2.0)
      mime-types (>= 1.16, < 4.0)
      netrc (~> 0.8)
    retriable (3.1.1)
    rgeo (0.6.0)
    rong_cloud_server (0.2.1)
    roo (2.7.1)
      nokogiri (~> 1)
      rubyzip (~> 1.1, < 2.0.0)
    rqrcode (0.10.1)
      chunky_png (~> 1.0)
    rqrcode_png (0.1.5)
      chunky_png
      rqrcode
    rspec (3.6.0)
      rspec-core (~> 3.6.0)
      rspec-expectations (~> 3.6.0)
      rspec-mocks (~> 3.6.0)
    rspec-core (3.6.0)
      rspec-support (~> 3.6.0)
    rspec-expectations (3.6.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.6.0)
    rspec-mocks (3.6.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.6.0)
    rspec-rails (3.6.1)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 3.6.0)
      rspec-expectations (~> 3.6.0)
      rspec-mocks (~> 3.6.0)
      rspec-support (~> 3.6.0)
    rspec-support (3.6.0)
    rubocop (0.58.2)
      jaro_winkler (~> 1.5.1)
      parallel (~> 1.10)
      parser (>= 2.5, != 2.5.1.1)
      powerpack (~> 0.1)
      rainbow (>= 2.2.2, < 4.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (~> 1.0, >= 1.0.1)
    rubocop-rails_config (0.2.1)
      railties (>= 3.0)
      rubocop (~> 0.56)
    ruby-ll (2.1.2)
      ansi
      ast
    ruby-progressbar (1.9.0)
    ruby-readability (0.7.0)
      guess_html_encoding (>= 0.0.4)
      nokogiri (>= 1.6.0)
    ruby_dep (1.5.0)
    rubyzip (1.2.1)
    safe_yaml (1.0.4)
    sass (3.4.25)
    sass-rails (5.0.6)
      railties (>= 4.0.0, < 6)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    searchkick (3.1.0)
      activemodel (>= 4.2)
      elasticsearch (>= 5)
      hashie
    select2-rails (3.5.10)
      thor (~> 0.14)
    sentry-raven (2.7.3)
      faraday (>= 0.7.6, < 1.0)
    serverengine (1.5.11)
      sigdump (~> 0.2.2)
    shellany (0.0.1)
    sidekiq (5.2.1)
      connection_pool (~> 2.2, >= 2.2.2)
      rack-protection (>= 1.5.0)
      redis (>= 3.3.5, < 5)
    sidekiq-cron (1.0.4)
      fugit (~> 1.1)
      sidekiq (>= 4.2.1)
    sidekiq-rate-limiter (0.1.2)
      redis_rate_limiter
      sidekiq (>= 2.0, < 6.0)
    sigdump (0.2.4)
    simple_form (3.5.0)
      actionpack (> 4, < 5.2)
      activemodel (> 4, < 5.2)
    sinatra (1.4.8)
      rack (~> 1.5)
      rack-protection (~> 1.4)
      tilt (>= 1.3, < 3)
    slim (3.0.8)
      temple (>= 0.7.6, < 0.9)
      tilt (>= 1.3.3, < 2.1)
    slop (3.6.0)
    sneakers (2.5.0)
      bunny (~> 2.6.4)
      serverengine (~> 1.5.11)
      thor
      thread (~> 0.1.7)
    spring (2.0.2)
      activesupport (>= 4.2)
    spring-commands-rspec (1.0.4)
      spring (>= 0.9.1)
    sprockets (3.7.1)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.1)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    sshkit (1.15.1)
      net-scp (>= 1.1.2)
      net-ssh (>= 2.8.0)
    temple (0.8.0)
    therubyracer (0.12.3)
      libv8 (~> 3.16.14.15)
      ref
    thin (1.7.2)
      daemons (~> 1.0, >= 1.0.9)
      eventmachine (~> 1.0, >= 1.0.4)
      rack (>= 1, < 3)
    thor (0.20.0)
    thread (0.1.7)
    thread_safe (0.3.6)
    tilt (2.0.8)
    timecop (0.9.1)
    tool (0.2.3)
    tzinfo (1.2.5)
      thread_safe (~> 0.1)
    uglifier (3.2.0)
      execjs (>= 0.3.0, < 3)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.4)
    unicode-display_width (1.4.0)
    uniform_notifier (1.10.0)
    virtus (1.0.5)
      axiom-types (~> 0.1)
      coercible (~> 1.0)
      descendants_tracker (~> 0.0, >= 0.0.3)
      equalizer (~> 0.0, >= 0.0.9)
    warden (1.2.7)
      rack (>= 1.0)
    webmock (3.0.1)
      addressable (>= 2.3.6)
      crack (>= 0.3.2)
      hashdiff
    xpath (2.1.0)
      nokogiri (~> 1.3)

PLATFORMS
  ruby

DEPENDENCIES
  aasm
  actionpack-action_caching
  actionpack-page_caching
  active_attr
  active_interaction (~> 3.4)
  activejob_backport
  activerecord-import
  addressable
  airbrake (~> 6.2)
  awesome_print
  better_errors
  bh (~> 1.2)
  binding_of_caller
  bootflat-rails (~> 0.2.1)
  bootstrap-kaminari-views
  bootstrap-sass (~> 3.3.6)
  browser
  bson_ext
  bullet
  cancancan
  capistrano
  capistrano-bundler
  capistrano-passenger
  capistrano-rails (~> 1.1)
  capistrano-rvm
  capistrano-sidekiq
  capistrano-sneakers!
  capybara
  cocoon
  coffee-rails (~> 4.0.0)
  colorize
  compass-rails
  config
  dalli
  database_cleaner
  devise
  dotenv-rails
  enumerize
  factory_girl_rails
  faker
  font-awesome-rails
  geocoder
  gon
  grape (= 0.19.1)
  grape-entity
  grape-jbuilder
  grape-kaminari (= 0.1.9)
  grape-route-helpers (= 2.0.0)
  grape-swagger!
  grape-swagger-entity
  grape-swagger-rails
  grape_logging
  grim
  guard-rspec
  guard-rubocop
  hashie-forbidden_attributes
  hiredis (~> 0.4.5)
  ionicons-rails
  jbuilder (= 2.1.1)
  jquery-rails
  json-schema
  json_spec
  kaminari-actionview
  kaminari-activerecord
  kaminari-grape
  kaminari-mongoid
  launchy
  letter_opener_web (~> 1.2.0)
  logstash-logger
  mini_magick
  money-rails
  mongoid (~> 5.0)
  mongoid-autoinc
  mongoid-geospatial
  mongoid-locker
  mongoid-rspec
  mongoid-tree
  mongoid_paranoia
  mysql2 (~> 0.4.0)
  nokogiri (= 1.6.6.2)
  oga
  oj
  parallel
  parallel_tests
  phonelib
  photoswipe-rails (~> 4.1, >= 4.1.1)
  pili
  pingpp!
  premailer-rails
  protobuf
  pry
  pry-nav
  pry-rails
  public_activity
  qiniu!
  quiet_assets
  rack-cors
  rails (= 4.2.5)
  rchardet19
  redis (~> 3.2)
  rest-client
  retriable (~> 3.0)
  rgeo
  rong_cloud_server (~> 0.2)
  roo
  rqrcode
  rqrcode_png
  rspec-rails
  rubocop-rails_config
  ruby-progressbar
  ruby-readability
  sass-rails (= 5.0.6)
  searchkick (~> 3)
  select2-rails
  select2_simple_form!
  sentry-raven
  sidekiq
  sidekiq-cron
  sidekiq-rate-limiter
  simple_form
  sinatra
  slim
  sneakers
  spring
  spring-commands-rspec
  therubyracer
  thin
  tilt-jbuilder!
  timecop
  uglifier (>= 1.3.0)
  webmock
  x-editable-rails!

RUBY VERSION
   ruby 2.3.1p112

BUNDLED WITH
   1.16.6
```

**Comment by ankane** [comment]
Hey @Awlter, removing activejob_backport should fix the issues.

**Comment by Awlter** [comment]
Hi, @ankane , it still doesn't seem to work after removing the gem.

Here are the params info
```
{
  "context": "Job raised exception",
  "job": {
    "args": [
      {
        "arguments": [
          {
            "class_name": "Accession"
          }
        ],
        "job_class": "Searchkick::ProcessQueueJob",
        "job_id": "967d9773-a92c-429b-b118-95c22262cbcd",
        "queue_name": "staging_searchkick"
      }
    ],
    "class": "ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper",
    "created_at": "1539614165.5940037",
    "enqueued_at": "1539615536.7933285",
    "error_class": "ArgumentError",
    "error_message": "wrong number of arguments (given 1, expected 0)",
    "failed_at": "1539614165.5999177",
    "jid": "18f0e53c09386b7522c8ee0d",
    "queue": "staging_searchkick",
    "retried_at": "1539614794.6120381",
    "retry": true,
    "retry_count": "5"
  },
  "jobstr": "{\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"queue\":\"staging_searchkick\",\"args\":[{\"job_class\":\"Searchkick::ProcessQueueJob\",\"job_id\":\"967d9773-a92c-429b-b118-95c22262cbcd\",\"queue_name\":\"staging_searchkick\",\"arguments\":[{\"class_name\":\"Accession\"}]}],\"retry\":true,\"jid\":\"18f0e53c09386b7522c8ee0d\",\"created_at\":1539614165.5940037,\"enqueued_at\":1539615536.7933285,\"error_message\":\"wrong number of arguments (given 1, expected 0)\",\"error_class\":\"ArgumentError\",\"failed_at\":1539614165.5999177,\"retry_count\":5,\"retried_at\":1539614794.6120381}",
  "thread": {
    "fiber_variables": {
      "ActiveSupport::Notifications::InstrumentationRegistry": "#<ActiveSupport::Notifications::InstrumentationRegistry:0x007fe66476d4a8>",
      "ActiveSupport::SubscriberQueueRegistry": "#<ActiveSupport::SubscriberQueueRegistry:0x007fe66476d2c8>",
      "activesupport_tagged_logging_tags": [],
      "current-60201360-count": "1",
      "i18n_config": "#<I18n::Config:0x007fe66476e0b0>",
      "sidekiq_context": [],
      "sidekiq_label": "processor",
      "sidekiq_tid": "ox9o206y8"
    },
    "group": [
      "#<Thread:0x000000023da1b0 sleep>",
      "#<Thread:0x0000000f755080@/home/deploy/rails/magnet/shared/bundle/ruby/2.3.0/gems/sidekiq-5.2.1/lib/sidekiq/util.rb:23 sleep>",
      "#<Thread:0x0000000f754ef0@/home/deploy/rails/magnet/shared/bundle/ruby/2.3.0/gems/sidekiq-5.2.1/lib/sidekiq/util.rb:23 sleep>",
      "#<Thread:0x0000000eb4de90@/home/deploy/rails/magnet/shared/bundle/ruby/2.3.0/gems/sidekiq-5.2.1/lib/sidekiq/util.rb:23 sleep>",
      "#<Thread:0x0000000e3e8998@/home/deploy/rails/magnet/shared/bundle/ruby/2.3.0/gems/mongo-2.6.2/lib/mongo/server/monitor.rb:136 sleep>",
      "#<Thread:0x007fe668223ac0@/home/deploy/rails/magnet/shared/bundle/ruby/2.3.0/gems/mongo-2.6.2/lib/mongo/server/monitor.rb:136 sleep>",
      "#<Thread:0x007fe6682234f8@/home/deploy/rails/magnet/shared/bundle/ruby/2.3.0/gems/mongo-2.6.2/lib/mongo/server/monitor.rb:136 sleep>",
      "#<Thread:0x007fe6682226c0@/home/deploy/rails/magnet/shared/bundle/ruby/2.3.0/gems/mongo-2.6.2/lib/mongo/cluster/periodic_executor.rb:97 sleep>",
      "#<Thread:0x007fe658090538@/home/deploy/rails/magnet/shared/bundle/ruby/2.3.0/gems/mongo-2.6.2/lib/mongo/server/monitor.rb:136 sleep>",
      "#<Thread:0x0000000e3b3a90@/home/deploy/rails/magnet/shared/bundle/ruby/2.3.0/gems/mongo-2.6.2/lib/mongo/server/monitor.rb:136 sleep>",
      "#<Thread:0x0000000e3b31f8@/home/deploy/rails/magnet/shared/bundle/ruby/2.3.0/gems/mongo-2.6.2/lib/mongo/server/monitor.rb:136 sleep>",
      "#<Thread:0x0000000e3b1a10@/home/deploy/rails/magnet/shared/bundle/ruby/2.3.0/gems/mongo-2.6.2/lib/mongo/cluster/periodic_executor.rb:97 sleep>",
      "#<Thread:0x007fe668c46e08@/home/deploy/rails/magnet/shared/bundle/ruby/2.3.0/gems/sidekiq-5.2.1/lib/sidekiq/util.rb:23 sleep>",
      "#<Thread:0x007fe65e51b8b8@/home/deploy/rails/magnet/shared/bundle/ruby/2.3.0/gems/sidekiq-5.2.1/lib/sidekiq/util.rb:23 run>"
    ],
    "priority": "0",
    "safe_level": "0",
    "self": "#<Thread:0x007fe65e51b8b8@/home/deploy/rails/magnet/shared/bundle/ruby/2.3.0/gems/sidekiq-5.2.1/lib/sidekiq/util.rb:23 run>"
  }
}
```

**Comment by ankane** [comment]
It seems like something is interfering with keyword arguments in jobs. Are you able to create a background job in your app that uses them? ActiveJob should support keyword arguments as of Rails 4.2.1: https://github.com/rails/rails/issues/18741

**Comment by Awlter** [comment]
Hey, @ankane , it did resolve the problem by removing the gem. I have been observing for a whole day.

I think the reason why it seemed it didn't fix it immediately after removing is that there are still some incorrect jobs being executed at the moment. My bad.

Thanks a lot! It really saves me a lot of time.

**Comment by ankane** [comment]
👍
